### ISSUE TITLE
+版打包不成功

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/package-flippy-openwrt#3]
/usr/bin/sudo chmod -R 777 /opt/openwrt
/usr/bin/sudo mkdir -p /upload
/usr/bin/sudo chmod -R 777 /upload
 {"devices":"s905d","openwrt_version":"R21.6.22","kernel_version":"5.12.13-flippy-61","whoami":"doctor","out":"/upload","openwrt_path":"$GITHUB_WORKSPACE/openwrt/bin/targets/*/*","openwrt_url":"","sub_name":"mini"} }
/usr/bin/sudo ./mk_s905d_n1.sh
**/opt/kernel/modules-5.12.13-flippy-61.tar.gz not exists!**
(node:2353739) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/sudo' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/mingxiaoyu/package-flippy-openwrt/main/dist/index.js:950:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/mingxiaoyu/package-flippy-openwrt/main/dist/index.js:933:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/mingxiaoyu/package-flippy-openwrt/main/dist/index.js:827:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:2353739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2353739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mingxiaoyu** [comment]
内核参数要改用为5.12.13-flippy-61+
https://github.com/mingxiaoyu/flippy-packages ， 我已经重命名了文件夹的名字
如果fork的，自己改下吧。没测试，理论上应该会OK
